#!/bin/sh

command -v scrot &> /dev/null
if [ $? -ne 0 ]; then echo "scrot not found"; exit; fi

DIR=$HOME/screenshots
if [ ! -d "$DIR" ]; then echo "$DIR does not exist."; exit; fi

echo "Waiting 1 sec for screenshot..."
sleep 1

cd $DIR
scrot
