#!/usr/bin/python

import urllib.parse
import os, sys

if __name__ == "__main__":
   args = sys.argv[1:]
   if len(args) > 0:
      words = ' '.join(args)
      enc = urllib.parse.quote(words)
      os.execlp("firefox", "firefox", "-private-window", "https://www.wiktionary.org/wiki/" + enc)
   else:
      os.execlp("firefox", "firefox", "-private-window", "https://www.wiktionary.org/")
